### ISSUE TITLE
sync fails with "agent list id failed"

### ISSUE THREAD

**Issue by mjakl** [ierror/ssh-permit-a38#8]
When I try to sync my ssh keys with either version `0.1.0` or `0.2.0` I suddenly get this error. I can't really make sense out of it, though. I'm using the precompiled versions and am running it on Linux (Archlinux) - I was using a Mac before (worked fine).

Logging in manually with ssh works fine - note that I'm using a custom port (hardcoded into the hostname field in JSON) and different user than my current user to access my host (set during sync see below).

```
> RUST_BACKTRACE=1 ../bin/ssh-permit-a38 sync -y

# Syncing host XXXXXXXX...

SSH User (root): 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -43, msg: "agent list id failed" }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::result::unwrap_failed
   9: ssh_permit_a38::subcommand_sync::sync
  10: ssh_permit_a38::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: main
  16: __libc_start_main
  17: _start
```

**Comment by mjakl** [comment]
I don't get that error with `0.2.0` on an Ubuntu running in a WSL (Windows 10). Though, it seems that the script cannot work anymore with my `ed25519` keys?

```
> ../Downloads/ssh-permit-a38 sync -y

# Syncing host XXXXXXX...

SSH User (root):
Private key (/home/.../.ssh/id_rsa): id_ed25519
Passphrase (empty for no passphrase): Error: [-16] Unable to extract public key from private key file: Wrong passphrase or invalid/unrecognized private key file format
```

I was using an `ed25519` key on Mac as well (it worked the last time I used it).

With version `0.1.0` I get a different error on Ubuntu:

```
> ../Downloads/ssh-permit-a38 sync

# Syncing host XXXXXXXX...

Error: Permission denied (os error 13)
```

Does anything in here sound familiar? `ssh-permit-a38` is such a good idea, I'd love to keep using it.
